Add Uploadcare.mdx to avif.io
KamillaGarifullina/avif.io pull request #3
Opened 2022-06-27 11:01 UTC by KamillaGarifullina

2022-07-04 12:23 UTC, homm requested changes

2022-07-04 12:23 UTC, homm commented on blog/tutorials/uploadcare.mdx
> +  - https://stackshare.io/uploadcare
Насколько вижу, ссылки тут без `https://`

2022-07-04 12:23 UTC, homm commented on blog/tutorials/uploadcare.mdx
> +Uploadcare Image processing pipeline now supports AVIF images as a source. AVIF images can be uploaded when `imagesOnly` option is enabled.
> AVIF images can be uploaded when `imagesOnly` option is enabled.

Опция ни при чем.

2022-07-04 12:23 UTC, homm commented on blog/tutorials/uploadcare.mdx
> +Uploadcare Image processing pipeline now supports AVIF images as a source. AVIF images can be uploaded when `imagesOnly` option is enabled.
```suggestion
Uploadcare Image processing pipeline now supports AVIF images as a source. Processed images could also be served as AVIF using the `-/format/auto/` operation, if a client supports this and the image meets some circumstances.
```

2022-07-04 12:23 UTC, homm commented on blog/tutorials/uploadcare.mdx
> +By using AVIF, you are increasing your processing usage since AVIF is intensive to encode. Consequently, it takes longer for the processing to take place. The problem is noticeable with delays of a f
Этот абзац лучше убрать

2022-07-04 12:23 UTC, homm commented on blog/tutorials/uploadcare.mdx
> +                               ].join(',')
```suggestion
<Syntax language="html">
  {`<img srcset="https://ucarecdn.com/f70b3810-1f72-4ad3-97c9-fd1c9c24db6f/-/format/auto/-/resize/240x/ 240w,
             https://ucarecdn.com/f70b3810-1f72-4ad3-97c9-fd1c9c24db6f/-/format/auto/-/resize/400x/ 400w,
             https://ucarecdn.com/f70b3810-1f72-4ad3-97c9-fd1c9c24db6f/-/format/auto/-/resize/480x/-/quality/lightest/ 480w,
             https://ucarecdn.com/f70b3810-1f72-4ad3-97c9-fd1c9c24db6f/-/format/auto/-/resize/800x/-/quality/lightest/ 800w"
    sizes="(max-width: 820px) 240px, 400px"
    src="https://ucarecdn.com/f70b3810-1f72-4ad3-97c9-fd1c9c24db6f/-/resize/400x/"
    alt="Mountain lake">`}
</Syntax>
```

2022-07-05 07:38 UTC, KamillaGarifullina commented on blog/tutorials/uploadcare.mdx
> +  - https://stackshare.io/uploadcare
Убрала

2022-07-05 07:40 UTC, KamillaGarifullina commented on blog/tutorials/uploadcare.mdx
> +By using AVIF, you are increasing your processing usage since AVIF is intensive to encode. Consequently, it takes longer for the processing to take place. The problem is noticeable with delays of a f
Убрала

2022-07-06 09:50 UTC, homm approved these changes

2022-07-07 03:40 UTC, merged